services:
  - type: web
    name: firesearchia
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python inference.py
    envVars:
      - key: PORT
        value: 8001